version: "3"

services:
  mysqldb:
      container_name: mysqldb
      build:
        context: .
        dockerfile: MySQLDockerfile
      ports: 
        - "3306:3306"
      environment: 
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: node_mysql_ts
        MYSQL_USER: test
        MYSQL_PASSWORD: 123
      volumes: 
        - mysqldb-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports: 
      - "8000:80"
    environment: 
      PMA_USER: root 
      PMA_PASSWORD: secret
      PMA_HOST: mysqldb
    depends_on: 
      - mysqldb
    links: 
      - mysqldb
    logging: 
      driver: none
volumes: 
  mysqldb-data: